# Generated by Django 6.0.6 on 2026-07-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("IN_PROGRESS", "In progress"),
                    ("PENDING", "Pending"),
                    ("BLOCKED", "Blocked"),
                    ("DONE", "Done"),
                ],
                default="NEW",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("IN_PROGRESS", "In progress"),
                    ("PENDING", "Pending"),
                    ("BLOCKED", "Blocked"),
                    ("DONE", "Done"),
                ],
                default="NEW",
            ),
        ),
    ]
