# Generated by Django 6.0.6 on 2026-07-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_subtask_status_task_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="subtask",
            options={"verbose_name": "Subtask", "verbose_name_plural": "Subtasks"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Task", "verbose_name_plural": "Tasks"},
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(fields=("name",), name="unique_name"),
        ),
        migrations.AlterModelTable(
            name="category",
            table="task_manager_category",
        ),
        migrations.AlterModelTable(
            name="subtask",
            table="task_manager_subtask",
        ),
        migrations.AlterModelTable(
            name="task",
            table="task_manager_task",
        ),
    ]
