# Generated by Django 6.0.6 on 2026-07-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_category_options_alter_subtask_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="deadline",
            field=models.DateTimeField(null=True, verbose_name="Deadline"),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(null=True, verbose_name="Deadline"),
        ),
        migrations.AlterModelTable(
            name="category",
            table="task_manager_categorys",
        ),
        migrations.AlterModelTable(
            name="subtask",
            table="task_manager_subtasks",
        ),
        migrations.AlterModelTable(
            name="task",
            table="task_manager_tasks",
        ),
    ]
