# Generated by Django 6.0.6 on 2026-07-31 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_alter_subtask_deadline_alter_task_deadline_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subtask",
            old_name="deadline",
            new_name="dead_line",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="deadline",
            new_name="dead_line",
        ),
    ]
